ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
ansible_user: inetronix
db_name: employee_db
db_user: db_user
db_user_password: Passw0rd
login_user: root
login_password: Passw0rd
gce_project_id: clear-basis-382009
gcp_cred_kind: serviceaccount
gcp_cred_file: /tmp/ansible-service-account.json
gcp_service_account_email: ansible-service-account@clear-basis-382009.iam.gserviceaccount.com
machine_type: n1-standard-1
zone: "us-central1-a"
region: "us-central1"
image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
web_instances:
  - web-server-1
  - web-server-2
db_instances:
  - db-server
scopes: 'https://www.googleapis.com/auth/compute'
