- name: Setup networking
  hosts: localhost
  tasks:
    - name: Get VPC network details
      google.cloud.gcp_compute_network_info:
        filters:
          - name = default
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: network_info
      delegate_to: localhost

    - name: Allow HTTP traffic
      google.cloud.gcp_compute_firewall:
        name: "allow-http"
        network:
          selfLink: "{{ network_info.resources[0].selfLink }}"
        allowed:
          - ip_protocol: tcp
            ports: ["80"]
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      delegate_to: localhost

    - name: create web instances
      include_tasks: create web_server_instances.yaml
      loop: "{{ web_instances }}"
      loop_control:
        loop_var: instance_name

    - name: Create Load balancer
      gce_lb:
        name: "my-load-balancer"
        region: "us-central1"
        protocol: "TCP"
        port_range: "80-80"
        members: ["us-central1-a/web-server-1", "us-central1-a/web-server-2"]
        project_id: "{{ gcp_project }}"
        service_account_email: "{{ gcp_service_account_email }}"
        credentials_file: "{{ gcp_cred_file }}"
        state: present
      delegate_to: localhost

    - name: Print Message
      debug:
        msg:
          gce_lb:
            name: "my-load-balancer"
            region: "us-central1"
            protocol: "TCP"
            port_range: "80-80"
            members: [ "us-central1-a/web-server-1", "us-central1-a/web-server-2" ]
            project_id: "{{ gcp_project }}"
            service_account_email: "{{ gcp_service_account_email }}"
            credentials_file: "{{ gcp_cred_file }}"
            state: present
          delegate_to: localhost







