- name: Install and configure MySQL Database
  hosts:
    - db_servers
  become: yes
  become_method: sudo
  tasks:
    - name: Include sensitive variables
      include_vars:
        file: secrets.yml
  roles:
    - python
    - mysql_db

- name: Install and configure webserver
  hosts:
    - web_servers
  become: yes
  become_method: sudo
  tasks:
    - name: Include sensitive variables
      include_vars:
        file: secrets.yml
  roles:
    - python
    - flask_web



