- name: Install and configure MySQL Database
  hosts:
    - db_servers
  become: yes
  become_method: sudo
  roles:
    - python
    - mysql_db

- name: Install and configure webserver
  hosts:
    - web_servers
  become: yes
  become_method: sudo
  roles:
    - python
    - flask_web



