- name: Setup networking
  hosts: localhost
  tasks:
   - name: Allow HTTP traffic
     google.cloud.gcp_compute_firewall:
       name: "allow-http"
       network: "default"
       allowed:
         - IPProtocol: tcp
           ports:
             - "80"
       project: "{{ gcp_project }}"
       auth_kind: "{{ gcp_cred_kind }}"
       service_account_file: "{ { gcp_cred_file } }"
       state: present
     delegate_to: localhost
