- name: Setup networking
  hosts: localhost
  tasks:
    - name: Get VPC network details
      google.cloud.gcp_compute_network_info:
        filters:
          - name = default
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: network_info
      delegate_to: localhost

    - name: Allow HTTP traffic
      google.cloud.gcp_compute_firewall:
        name: "allow-http"
        network:
          selfLink: "{{ network_info.resources[0].selfLink }}"
        allowed:
          - ip_protocol: tcp
            ports: ["80"]
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      delegate_to: localhost




