- name: Install and configure MySQL Database
  hosts:
    - db-server
  become: yes
  become_method: sudo
  roles:
    - python
    - mysql_db

- name: Install and configure MySQL Database
  hosts:
    - web-server-1
    - web-server-2
  become: yes
  become_method: sudo
  roles:
    - python
    - flask_web



