- name: Setup sensitive variables
  hosts: localhost
  tasks:
    - name: Include sensitive variables
      include_vars:
        file: secrets.yml

- name: Import deploy-gcp-instances playbook
  import_playbook: deploy-gcp-instances.yaml

- name: Import configure-application-servers playbook
  import_playbook: configure-application-servers.yaml

- name: Import configure networking playbook
  import_playbook: configure-networking.yml


