---
- name: Test instances Connectivity
  hosts:
    - db-server
    - web-server-1
    - web-server-2
  vars:
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
    ansible_user: inetronix

  tasks:
    - name: Ping all servers
      ansible.builtin.ping:
