- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars:
    gcp_project: clear-basis-382009
    gcp_cred_kind: "{{ lookup('env', 'GCP_AUTH_KIND') }}"
    gcp_cred_file: "{{ lookup('env', 'GCP_SERVICE_ACCOUNT_FILE') }}"
    machine_type: n1-standard-1
    zone: "us-central1-a"
    region: "us-central1"
    image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
    web_instance: web-server-1,web-server-2
    db_instances: db-server
    scopes: 'https://www.googleapis.com/auth/compute'

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 10
         source_image: "{{ image }}"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes: "{{ scopes }}"
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes: "{{ scopes }}"
         state: present
     register: address
   - name: create web instances
     gcp_compute_instance:
         state: present
         name: "{{ item }}"
         machine_type: "{{ machine_type }}"
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes: "{{ scopes }}"
     loop:
       - web-server-1
       - web-server-2
     register: web_deploy_result

   - name: create db instance
     gcp_compute_instance:
       state: present
       name: "{{ db_instance }}"
       machine_type: "{{ machine_type }}"
       disks:
         - auto_delete: true
           boot: true
           source: "{{ disk }}"
       network_interfaces:
         - network: null # use default
           access_configs:
             - name: 'External NAT'
               nat_ip: "{{ address }}"
               type: 'ONE_TO_ONE_NAT'
       zone: "{{ zone }}"
       project: "{{ gcp_project }}"
       auth_kind: "{{ gcp_cred_kind }}"
       service_account_file: "{{ gcp_cred_file }}"
       scopes: "{{ scopes }}"
     register: db_deploy_result

   - name: display results
     debug:
       msg:
         - web_deploy_result
         - db_deploy_result

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances


