- name: Deploy a distributed web application
  hosts: localhost
  gather_facts: false
  tasks:
   - name: create web instances
     include_tasks: create web_server_instances.yaml
     loop: "{{ web_instances }}"
     loop_control:
       loop_var: instance_name

   - name: create db instances
     include_tasks: create db_server_instance.yaml
     loop: "{{ db_instances }}"
     loop_control:
       loop_var: instance_name

   - name: display results
     debug:
       msg:
         - "{{ web_deploy_result }}"
         - "{{ db_deploy_result }}"

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances