- name: Deploy a distributed web application
  hosts: localhost
  gather_facts: false
  vars:
    gcp_project: clear-basis-382009
    machine_type: n1-standard-1
    zone: "us-central1-a"
    region: "us-central1"
    image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
    web_instances:
      - web-server-1
      - web-server-2
    db_instances:
      - db-server
    scopes: 'https://www.googleapis.com/auth/compute'

  tasks:
    - name: Authenticate with GCP
      google.cloud.gcp_auth:
        project: "{{ gcp_project }}"
        service_account_file: "{{ lookup('env', 'GCP_SERVICE_ACCOUNT_FILE') }}"

    - name: create web instances
     include_tasks: create web_server_instances.yaml
     loop: "{{ web_instances }}"
     loop_control:
       loop_var: instance_name

   - name: create db instances
     include_tasks: create db_server_instance.yaml
     loop: "{{ db_instances }}"
     loop_control:
       loop_var: instance_name

   - name: display results
     debug:
       msg:
         - "{{ web_deploy_result }}"
         - "{{ db_deploy_result }}"

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances
