- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars:
      gcp_project: clear-basis-382009
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /tmp/ansible-service-account.json
      zone: "us-central1-a"
      region: "us-central1"

  tasks:
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             initialize_params:
               disk_size_gb: 10
               source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances

- name: Manage new instances
  hosts: new_instances
  connection: ssh
  become: True
  roles:
