---
    - name: Install MySQL database
      apt:
        name: ['mysql-server', 'mysql-client-core-8.0', 'mysql-client']
        state: present

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install PyMySQL
      apt:
        name: python3-mysql.connector
        state: present

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: pymysql
        state: present
      become: yes

    - name: Update MySQL configuration file with bind-address
      ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: bind-address
        value: 0.0.0.0
      become: yes
      become_method: sudo

    - name: Update MySQL configuration file with port
      ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: port
        value: 3306
      become: yes
      become_method: sudo

    - name: Update MySQL configuration file with mysqlx-bind-address
      ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: mysqlx-bind-address
        value: 0.0.0.0
      become: yes
      become_method: sudo

    - name: Restart MySQL service
      ansible.builtin.systemd:
        name: mysql
        state: restarted
      become: yes
      become_method: sudo

    - name: Install python3-mysqldb
      ansible.builtin.apt:
        name: python3-mysqldb
        state: present
        update_cache: yes

    - name: Copy .my.cnf file to the target server
      ansible.builtin.copy:
        src: my.cnf.j2
        dest: /root/.my.cnf
        mode: 0600
        owner: root
        group: root
      vars:
        mysql_user: root
        mysql_password: Passw0rd

    - name: Create Application Database
      community.mysql.mysql_db:
        name: employee_db
        state: present
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"

    - name: Create Application DB User
      community.mysql.mysql_user:
        name: db_user
        host: '%'
        password: db_user_password
        state: present
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"

    - name: Grant all privileges on employee_db to db_user
      community.mysql.mysql_user:
        name: db_user
        host: '%'
        priv: "employee_db.*:ALL"
        state: present
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"

