---
    - name: Install MySQL database
      apt:
        name: ['mysql-server', 'mysql-client-core-8.0', 'mysql-client']
        state: present

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install PyMySQL
      apt:
        name: python3-mysql.connector
        state: present

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: pymysql
        state: present
      become: yes

    - name: Update MySQL configuration file with bind-address
      ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: bind-address
        value: 0.0.0.0
      become: yes
      become_method: sudo

    - name: Update MySQL configuration file with port
      ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: port
        value: 3306
      become: yes
      become_method: sudo

    - name: Update MySQL configuration file with mysqlx-bind-address
      ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: mysqlx-bind-address
        value: 0.0.0.0
      become: yes
      become_method: sudo

    - name: Restart MySQL service
      ansible.builtin.systemd:
        name: mysql
        state: restarted
      become: yes
      become_method: sudo

    - name: Install python3-mysqldb
      ansible.builtin.apt:
        name: python3-mysqldb
        state: present
        update_cache: yes

    - name: Copy .my.cnf file to the target server
      ansible.builtin.copy:
        src: my.cnf.j2
        dest: /root/.my.cnf
        mode: 0600
        owner: root
        group: root
      vars:
        mysql_user: root
        mysql_password: Passw0rd

    - name: Ensure MySQL root user can login with password
      ansible.builtin.mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        host: "{{ item }}"
        password: Passw0rd
        priv: "*.*:ALL,GRANT"
        state: present
      loop:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Grant all privileges to the MySQL user
      mysql_user:
        login_user: root
        login_password: Passw0rd
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        host: '%'
        priv: "*.*:ALL,GRANT"
        state: present
      become: yes
      become_method: sudo



    - name: Create Application Database
      mysql_db:
        name: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_user_password }}"
        login_host: 104.198.158.121
        login_port: '3306'
        state: present

    - name: Create Application DB User
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'
      no_log: True
