---
    - name: Install MySQL database
      apt:
        name: ['mysql-server', 'mysql-client']
        state: present

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install PyMySQL
      apt:
        name: python3-mysql.connector
        state: present

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: pymysql
        state: present
      become: yes

    - name: Create Application Database
      ansible.builtin.mysql_db:
        name: {{ db_name }}
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_user_password }}"
        login_host: 127.0.0.1
        login_port: 3306

    - name: Create Application Database
      mysql_db: name={{ db_name }} state=present

    - name: Create Application DB User
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'
